/*

 tiles.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#define tilesSize 2

/* Start of tile array. */
unsigned char tiles[] =
{
  // X pattern
  0x81,0x00,0x42,0x00,0x00,0x24,0x18,0x18,
  0x18,0x18,0x00,0x24,0x42,0x00,0x81,0x00,
  // Vertical line pattern
  0x18,0x00,0x18,0x00,0x18,0x00,0x18,0x00,
  0x18,0x00,0x18,0x00,0x18,0x00,0x18,0x00
};

/* End of tiles.C */
